Fix Max lookback issue (#178)
* Do not cross metric day boundaries.

* Merge day boundary (#146)

* Address issue #126. Allow pyomicron to run from a frame cache without accessing dqsegdb. Add documentation for this

* Do not merge files if they overlap "metric days"

* Do not cross metric day boundaries.

Co-authored-by: Joseph Areeda <joseph.areeda@ligo.org>

* Check point merge (#147)

* Do not cross metric day boundaries.

* add log file arg delete empty directories when done

* Tweak remove empty dir removal

* Tweak remove empty dir removal again

* Merge day boundary (#146)

* Address issue #126. Allow pyomicron to run from a frame cache without accessing dqsegdb. Add documentation for this

* Do not merge files if they overlap "metric days"

* Do not cross metric day boundaries.

Co-authored-by: Joseph Areeda <joseph.areeda@ligo.org>

* rebase agaist last approved PR

* rebase against last approved PR

* rebase against last approved PR again, fix flake8

* Fix a bug in remove empty directories.

Co-authored-by: Joseph Areeda <joseph.areeda@ligo.org>

* Merge day boundary (#146)

* Address issue #126. Allow pyomicron to run from a frame cache without accessing dqsegdb. Add documentation for this

* Do not merge files if they overlap "metric days"

* Do not cross metric day boundaries.

Co-authored-by: Joseph Areeda <joseph.areeda@ligo.org>

* minor doc changes

* Fix a bug where an xml.gz file could get compressed again in merge-with-gaps

* Fix a double gzip of ligolw files (#151)

* Do not cross metric day boundaries.

* Merge day boundary (#146)

* Address issue #126. Allow pyomicron to run from a frame cache without accessing dqsegdb. Add documentation for this

* Do not merge files if they overlap "metric days"

* Do not cross metric day boundaries.

Co-authored-by: Joseph Areeda <joseph.areeda@ligo.org>

* Check point merge (#147)

* Do not cross metric day boundaries.

* add log file arg delete empty directories when done

* Tweak remove empty dir removal

* Tweak remove empty dir removal again

* Merge day boundary (#146)

* Address issue #126. Allow pyomicron to run from a frame cache without accessing dqsegdb. Add documentation for this

* Do not merge files if they overlap "metric days"

* Do not cross metric day boundaries.

Co-authored-by: Joseph Areeda <joseph.areeda@ligo.org>

* rebase agaist last approved PR

* rebase against last approved PR

* rebase against last approved PR again, fix flake8

* Fix a bug in remove empty directories.

Co-authored-by: Joseph Areeda <joseph.areeda@ligo.org>

* Merge day boundary (#146)

* Address issue #126. Allow pyomicron to run from a frame cache without accessing dqsegdb. Add documentation for this

* Do not merge files if they overlap "metric days"

* Do not cross metric day boundaries.

Co-authored-by: Joseph Areeda <joseph.areeda@ligo.org>

* minor doc changes

* Fix a bug where an xml.gz file could get compressed again in merge-with-gaps

* Implement a periodic vacate to address permanent D-state (uninterupptible wait) causing jobs to fail to complete

* Always create a log file. If not specified put one in the output directory

* Fix a problem with periodic vacate.

* Up the periodic vacate time to 3 hrs

* Found a job killing typo

* Add time limits to post processing also

* Don't save segments.txt file if no sgments founds because we don't know if it's an issue of not finding them or a valid not analyzable state.

* disable periodic vacate to demo the problem.

* Fix reported version in some utilities. Only update segments.txt if omicron is actually run.

* Clarify relative imports. and add details to a few log messages

* Resolve flake8 issues

---------

Co-authored-by: Joseph Areeda <joseph.areeda@ligo.org>

* Resolve flake8 issues

* Update log format to use human readble date/time instead of gps
tweak logging to better underst guardian channel usage-

* remove old setup.cfg

* Work vonpytest failures. The remaining errors are the result of omicron segfaults if environment variable not set

* missing blank line, from flake8

* Fix a problem wit hmax-online-lookback not working properly in all pathes. Add some uman readable date/times to gps messages

* Fix logging problems from different gps time objects

* Better logging why online effort did not run

* Up default lookback window to 40 min

* Up default maximum lookback window to 60 min. Better logging of why we did not run.

* Fix flake8 and more logging updates

* Fix flake8 and more logging updates

* More logging updates

* More logging updates, paths through could cause error

* Trap and print errors from main()

* fix dag submission command

* add smart postscript to allow retries befor ignoring errors

* tst version of scitokens and smart post script

* tst version of scitokens and smart post script

* add arg to specify auth type (x5099, vault or apissuer)

* memopry units in the wrong place

* memory units in the wrong place, condor_run

* flake8 nit picked

* Again try to get periodic_release and periodic_remove correct

* Sort console scripts

* Typo in periodic_remove

* Better error message when programs not available

* implement cona run for all jobs in dag

* conda run complications with  cvmfs

* archive.py deals with renamed trigger files

* archive.py deals with renamed trigger files take 2

* condor run needed in all scripts.

* minor logging changes

* working on archive  issues

* working on archive  issues, keep "temporary" files to help debugging

* more logging

* Default max lookback changed to 30min. more logging tweaks

* Add omicron_utils to insta;; requirements

* Work on build and test workflow error.

* Still working on build and test workflow error. Remove Python 3.9 from workflows

* Set loglevel for OmicronConfig to Critical so --version command is clean

* Resolve all conversations

* try to deal with github error
```
Error: This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v2`. Learn more: https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/

```

* try to deal with github error
```
Error: This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v2`. Learn more: https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/

```

---------

Co-authored-by: Joseph Areeda <joseph.areeda@ligo.org>